### ISSUE TITLE
Dynamic data with flexible size

### ISSUE THREAD

**Issue by clairecoloma** [nuno/TiCollectionView#44]
Hi @mpociot, thank you for your great module.

I wonder the reason why we have to fix the size of an item?
And why can't we just use Ti.UI.SIZE?

Is that possible to add these lines to the CollectionView.m to set size of each item?
https://github.com/appcelerator/titanium_mobile/blob/master/iphone%2FClasses%2FTiUIListView.m#L1616

Cheers

**Comment by nuno** [comment]
@clairecoloma,
there are some ways to do so,  you can use

alloy.js
```
Alloy.Globals.singleCardDimentions = Ti.Platform.displayCaps.platformHeight;
Ti.API.info('singleCardDimentions  : ', Alloy.Globals.singleCardDimentions);
```


tss
```
// ListItem template
"#template":{
	height: Alloy.Globals.singleCardDimentions
}
```


or you can play with  ```Ti.UI.FILL / Ti.UI.SIZE``` with Views inside or the itemTemplate
