### ISSUE TITLE
Run on main thread need to be implemented

### ISSUE THREAD

**Issue by nuno** [nuno/TiCollectionView#59]
If we use <run-on-main-thread>true</run-on-main-thread> in tiapp.xml the module unfortunately it does not work. @mpociot  @viezel @adesugbaa Any help is appreciated!

**Comment by AppWerft** [comment]
OK, it is possible to realize. Look to my tutorial. https://github.com/AppWerft/TitaniumAndroidModuleDevelopment/blob/master/04-WaterWaveProgress.md

**Comment by hansemannn** [comment]
I'll take a look 😉

**Comment by nuno** [comment]
@hansemannn You the man!

**Comment by hansemannn** [comment]
Basically what you guys need is to use `ENSURE_UI_THREAD` in some places for the correct threading behavior, especially for UI-related manipulations. And you use some mutex locks (`pthread_mutex`) that can cause problems across some places when running on main thread.

You can search the Titanium Core for `ENSURE_UI_THREAD` and `TI_USE_KROLL_THREAD` to see where and how we use those. Not sure when I will find time for a closer look, so this should guide you in the correct direction.

**Comment by nuno** [comment]
Thank you for your time @hansemannn !

**Comment by hansemannn** [comment]
Will look into it this week. What else are critical iOS issues in here? A prioritized list would be cool. Thanks!

**Comment by nuno** [comment]
I Have a few things yeah. I will put in list.
One think I want this module be able to do is change the layout on the fly, ex, like pinterest

You have list of grid-layout, then you click one grid and change to horizontal-layout (kinda of scrollableView) that you can swipe to one by one item.

**Comment by hansemannn** [comment]
The example works using #66, please try it out!
