### ISSUE TITLE
Really struggling to get Waterfall working on Android

### ISSUE THREAD

**Issue by scottybo** [nuno/TiCollectionView#60]
I'm really struggling to get the Waterfall view working on Android. Testing on emulator for Nexus 5 and on a real Galaxy Note 3.

The problems are as follows (screenshots below):
- The list items don't have equal spacing above/below and often overlap
- When scrolling items out of/into view their positions change and sometimes disappear out of the top of the list view

![screenshot from 2016-04-04 17 06 16](https://cloud.githubusercontent.com/assets/11498904/14254608/73b24692-fa88-11e5-8abc-f04c778342be.png)

My code for initiating the collection view is as follows (contained in index.js)

`
var collectionView = require("de.marcelpociot.collectionview");
var cardListTemplate = getCardListTemplate();

// Create the Collection View
var listView = require("CollectionView").createCollectionView({
    backgroundColor: "#F2F2F2", 
    top: '40dp', 
    left: '5%', 
    width: "90%", 
    height: Ti.UI.FILL,

```
templates: { 'template': cardListTemplate },
defaultItemTemplate: 'template',

// Waterfall specific configuration
layout: 'LAYOUT_WATERFALL', 
columnCount: 2, 
minimumColumnSpacing: 40, 
minimumInteritemSpacing: 40, 
renderDirection: "DIRECTION_SHORTEST_FIRST",

// Android Only (required to stop the app crashing!)
columnWidth: 300, 
verticalSpacing: 40, 
horizontalSpacing: 40,
```

});

// Create the (empty) Collection Section
var productSection = collectionView.createCollectionSection(); 
var sections = [];

// Add the empty Collection to the index to reference next
sections.push(productSection);
listView.setSections(sections);

$.index.add(listView);
`
The contents are then dynamically loaded via a JSON call, with the basic action to add a new data set to the list view.

I'm doing entire output via index.js, so the index.xml doesn't reference the collection view:

`<Alloy>
    <Window backgroundColor="#F2F2F2">
        <View backgroundColor="#FC48A5" height="40dp" top="0">
            <Label color="#ffffff" icon="fa-bars" left="15dp">Open Menu</Label>
            <Label color="#ffffff" icon="fa-tags" right="55dp">My Interests</Label>
            <Label color="#ffffff" icon="fa-heart" right="35dp"/>
            <Label color="#ffffff" icon="fa-cog" right="15dp"/>
            <Widget id="fa" src="com.mattmcfarland.fontawesome"/>
        </View>
    </Window>
</Alloy>
`
Any help would be HUGELY appreciated as I'm currently stumped after trying everything I can think of.

**Comment by mohitcis** [comment]
Hi,
I am also facing the same issue in android. @scottybo did you get any solution of this issue.
If you got it. please let me know about it.
Thanks

**Comment by scottybo** [comment]
Unfortunately not - still haven't been able to figure it out :(

**Comment by mohitcis** [comment]
Hi @scottybo ,
Thanks for reply
Bad luck for us. If you will get any solution Please tell me about it.
Thanks

**Comment by scottybo** [comment]
Please also let me know if you find a solution or an alternative module :)

**Comment by mohitcis** [comment]
Yes sure @scottybo

**Comment by nuno** [comment]
Closed for now for missing activity :) 
I think "LAYOUT_WATERFALL" is just for ios, no?
