### ISSUE TITLE
Won't run on SDK6+

### ISSUE THREAD

**Issue by skoften** [nuno/TiCollectionView#65]
[WARN] :   Could not find a valid Titanium module id=de.marcelpociot.collectionview version=latest platform=iphone deploy-type=development
[ERROR] :  Found incompatible Titanium Modules:
[ERROR] :     id: de.marcelpociot.collectionview	 version: 1.4.1	 platform: ios,iphone	 min sdk: 3.5.1.GA

**Comment by hansemannn** [comment]
Just tested using #66, works fine! @nuno close?

**Comment by nuno** [comment]
@skoften If  you more issues please reopen.
