### ISSUE TITLE
isLazyLoadingEnabled - need implementation

### ISSUE THREAD

**Issue by nuno** [nuno/TiCollectionView#68]
isLazyLoadingEnabled is needed for the imageView, since this module share some ListView api

**Comment by hansemannn** [comment]
Should be pretty straight forward from the list-view implementation. I added it there back then, [here](https://github.com/appcelerator/titanium_mobile/pull/7320/files) is the PR.

**Comment by nuno** [comment]
Yup I have done that in one specific app that use this module.

**Comment by hansemannn** [comment]
Fixed in https://github.com/nuno/TiCollectionView/pull/66/commits/4c87ba2eb0479c981abedd2ff96cf03cde26abf0
