### ISSUE TITLE
Android module for sdk 6

### ISSUE THREAD

**Issue by MahmoudElmoghazy** [nuno/TiCollectionView#71]
I can't compile this module cause my studio have an issue and i can't fix it for now can any one compile this module for android 6 and upload it

**Comment by m1ga** [comment]
version 1.3.0 is 6+ ready!
https://github.com/nuno/TiCollectionView/tree/master/dist

**Comment by MahmoudElmoghazy** [comment]
@m1ga Thank u so much :)
