### ISSUE TITLE
Wrong layout

### ISSUE THREAD

**Issue by AhmedMSayed** [nuno/TiCollectionView#77]
@nuno @m1ga  thanks for resolving previous issues.
now if I set all items with the same height it's okay. but when I'm trying to set one item with different height it looked like this.
The layout should be formed before it appears in the list view not when scrolling.

Another question I'm set `renderDirection="DIRECTION_RIGHT_TO_LEFT" layout="LAYOUT_WATERFALL"` in the listView and there was no change.

![screenshot](https://user-images.githubusercontent.com/7584480/30967061-45ab37a8-a45b-11e7-8f92-b0fc95bcc715.png)

**Comment by m1ga** [comment]
@AhmedMohamed2014 sorry, can't help your there since I'm not using it, just made it work with the latest SDK 😄

**Comment by AhmedMohamed2014** [comment]
@m1ga no, I just wanted to say thanks for helping me with first issues 😄.

**Comment by nuno** [comment]
I think "LAYOUT_WATERFALL" is just for ios, no?
 Sorry  I'm not using it too :(

Like @m1ga I  just tried to make it work for you guys!

**Comment by AhmedMohamed2014** [comment]
No problem guys. thanks at all @nuno, but where is the module master.

**Comment by hansemannn** [comment]
The `LAYOUT_WATERFALL` constant is indeed iOS only, you cannot use it for other platforms.
