### ISSUE TITLE
Android is not 100% migrated to new module name

### ISSUE THREAD

**Issue by nuno** [nuno/TiCollectionView#79]
There are some files that still have:
@m1ga There is something that you can check when you have free time?
@ottopic issue https://github.com/nuno/TiCollectionView/issues/73

```
@Override
	public String getApiName()
	{
		return "de.marcelpociot.CollectionItem";
	}
```

https://github.com/nuno/TiCollectionView/blob/master/android/src/de/marcelpociot/collectionview/CollectionViewProxy.java#L437

**Comment by nuno** [comment]
@m1ga if you think this is not an issue, let me know :)

**Comment by m1ga** [comment]
see https://github.com/nuno/TiCollectionView/pull/80

**Comment by nuno** [comment]
Can I merge?

**Comment by m1ga** [comment]
yes, but it didn't fix the issue for me (Alloy is still working, even without the changes). But it will correct the naming

**Comment by nuno** [comment]
this can be bacause of folders naming? 
```/src/de/marcelpociot/collectionview```
  I do not know, Im not an android expert, thanks.

**Comment by m1ga** [comment]
No, thats not an issue. The problem is `item.setDefaultProperties(new KrollDict((HashMap)props));` that item is null in a vanilla project. Working fine in Alloy. Doing some tests at the moment to see what the source is

**Comment by nuno** [comment]
ok, is normal in manifest the "commonjs: true"  ?

**Comment by m1ga** [comment]
Can't find the issue. But this is where it goes wrong. Inside the `processProperties` of the CollectionViewTemplate there are some differences:

Properties of the alloy version:
```javascript
{"properties":{"name":"template"},"tiProxy":null,"childTemplates":[{"properties":{},"tiProxy":null,"type":"Ti.UI.View","childTemplates":[{"properties":{"height":"size","width":"size","font":{"fontSize":12},"bindId":"info","color":"#000"},"type":"Ti.UI.Label","tiProxy":null,"bindId":"info"},{"properties":{"height":"size","width":"size","top":"30dp","font":{"fontSize":12},"bindId":"es_info","color":"#000"},"type":"Ti.UI.Label","tiProxy":null,"bindId":"es_info"}]}]}
```

properties of the vanilla version:
```javascript
 {"childTemplates":[{"properties":{"top":10,"font":{"fontWeight":"bold","fontSize":20}},"type":"Ti.UI.Label","bindId":"info"},{"properties":{"top":40,"font":{"fontSize":14},"color":"gray"},"type":"Ti.UI.Label","bindId":"es_info"}]}
```

Perhaps someone else has a clue

**Comment by nuno** [comment]
Alright, thanks @m1ga!

**Comment by ottopic** [comment]
@m1ga any news about the issue? Have you tried to find a solution?

Best regards

**Comment by m1ga** [comment]
@ottopic no, sorry. If you can use the alloy version, that was working for me. But I'm not really using this module so I only tested the example
