### ISSUE TITLE
Can't build iOS module with Xcode

### ISSUE THREAD

**Issue by skoften** [nuno/TiCollectionView#83]
Several build errors :-(

![screen shot 2018-01-05 at 16 34 10](https://user-images.githubusercontent.com/1286410/34615874-91289c7e-f236-11e7-827e-c5b65afbef27.jpg)

**Comment by rlustemberg** [comment]
I think the typo is also on the sdk. Because the titaniumxcconfig is missing I don't know which sdk version this has been compiled to

**Comment by rlustemberg** [comment]
Compiling to 6.x.x contains the typo. 7.x has it fixed, and is in sync with your fix
